name: deploy-dev-branch
on:
    push:
        branches:
            - dev
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - run: nvm use 20.1.0
            - run: npm install
            - name: Deploy
              run: |
                  gatsby build
                   
                   
