name: Deploy dev branch
on:
    push:
        branches:
            - dev
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: gatsby build 
